spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: root

  jackson:
    default-property-inclusion: non_null

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher


jwt:
  secret: 83b91f1d-9c32-4bd6-9b5e-f643c2c8f3a5
  expiration: 999999